### ISSUE TITLE
WebDriver.__init__() got an unexpected keyword argument 'executable_path'

### ISSUE THREAD

**Issue by TheSalDave** [aminblm/linkedin-application-bot#17]
executable path was removed in the latest Selenium update.

https://stackoverflow.com/questions/76550506/typeerror-webdriver-init-got-an-unexpected-keyword-argument-executable-p

**Comment by alpersarac** [comment]
I solved the problem. can you try this. by replacing
self.driver = webdriver.Firefox(executable_path=GeckoDriverManager().install())
this line in LinkedIn.py
with:
self.driver = webdriver.Firefox(service=Service(executable_path=GeckoDriverManager().install()))

**Comment by wodsuz** [comment]
Hi,

This guy and the repo is against the community rules and the copyrighted work that belongs to me and my team.

He uses our name, code and guides in order to benefit himself.

The donation and payment links redirect to his own account that is fake and scam.

Please report this repo and guy as he has nothing to do with our work.

Team automated-bots - [www.automated-bots.com](http://www.automated-bots.com/)

**Comment by aminblm** [comment]
Thank you @TheSalDave and @alpersarac for checking this one out. I will review the PR and merge it.
